### ISSUE TITLE
Re: Router/Mifi Operatin System Cloning and Editing

### ISSUE THREAD

**Issue by niyonda** [osfree-project/osfree#113]
searching for ways to clone a router operating system. I'm quite a novice about all these, but I have a brilliant idea that I would like to try to make huge business out of. I would like you to put me through how to clone an operating system firmware from one device to another. And also how to edit the operating system and make changes I would like to effect. I would not mind giving you a founder's stake in the business of the internet data sharing business I'm about to go heavily into when it becomes profitable. Please show me the process to go through with this idea. Thank you, kindly. I await your reply.

**Comment by jcanfield** [comment]
Have you received any help? This post is two months old, just curious. There are some good resources out there. I started with Linux (Slackware & Debian) about 25 years ago (when I was around 14-15).

**Comment by niyonda** [comment]
Thank you for replying to my email. I have not receive any help yet. I
could use any help I can get at the moment. I am a newbie to tech and
everything associated to it. I just have an idea that I want to build up to
help students in my rural area get unmitigated access to the internet, so
we can stop missing classes and attend.
Please reply to me as soon as you can.
Thank you for your time.
Thank you, kindly.

**Comment by jcanfield** [comment]
For sure. It was truly random that I ended up seeing this issue. I remember playing around with OS/2 and BeOS when I was younger.

So, it sounds like you're looking at building an OS from scratch. I have to say that Linux is probably the best way to start. Here are some resources that might help get you going.

- [Linux From Scratch](https://www.linuxfromscratch.org/)
- [ReactOS](https://www.reactos.org/)
- [Haiku OS](https://haiku-os.org/)
- [Awesome List for OSes](https://github.com/jubalh/awesome-os)

So, the last list should be really helpful. There are a ton of hobby operating systems that have been started from scratch.

If you don't mind sharing, what are looking to build? It sounds like an embedded operating system. BSD could be an option.

**Comment by niyonda** [comment]
I don't mind sharing enough to get the help I need. I see the resources you
sent to me. And I'm grateful. But I must say, I might find it challenging
to make use of I think, because I'm all new to tech and I have not learnt
any substantial coding yet, only coding I knew is html from my 2007
computer classes.

So let me share and explain the idea better to you:
The idea is that I want to buy Internet data in bulk because it is cheap
and sells it in small units at a premium.
so I want to use pocket mifi to sell the internet data.
so I will buy the internet data on one sim card. let's say I buy 1,000GB.
so I will connect all the sim cards that's in the all the pocket mifis to
that one sim card where the bulk internet data is. so all the other sim
cards in all the pocket mifis will have direct access to the big bulk pool
internet data, but I want a software that can limit the use of the internet
data of each mifi to the amount of data each subscriber paid for.
for example, if one person pays for 10GB, I want them to be able to use
only the 10GB from the bulk pool of internet data, and after using it the
software will cut the mifi off from the bulk internet data, until they buy
another internet data bundle.
I hope you understand me well now.
if there is still something you don't understand, please let me know. I
could really use all the help I can get. I don't want this idea to die off
just because I don't have enough technical know-how.
Thank you, kindly.

**Comment by niyonda** [comment]
I also would like to ask, if you know how to use the flutterflow.io app
builder.
I awaits your reply.
Thank you, kindly.

**Comment by niyonda** [comment]
Good day. Please, I don't understand this email. Can you explain better.
What's 113? And why is it closed?
Thank you, kindly
Warm regards.

**Comment by prokushev** [comment]
Issue not related to osFree project in any way.

**Comment by niyonda** [comment]
You mean the flutterflow issue? Yes it isn't.  I just asked that in passing.

But please, check the previous chats I had with Joshua confield. It is
pertaining to osfree in some ways. I need the support with the project I
want to build that why I come running to OSfree.
Help out in the very way you possibly can.
Thank you, kindly.
