### ISSUE TITLE
License-file is missing

### ISSUE THREAD

**Issue by theuserbl** [osfree-project/osfree#2]
There is no license file in the osfree-repo nor is the license mentioned in the readme.md

**Comment by prokushev** [comment]
legal file in most places is license info

**Comment by theuserbl** [comment]
Hmmm... have a look at the license info of the header of
https://github.com/osfree-project/osfree/blob/master/OS2/Shared/all_messages.c
An "c) osFree Project 2002, <http://www.osFree.org>" is all.
At
https://github.com/osfree-project/osfree/blob/master/OS2/Shared/all_queryfsname.c
stands additional a "for licence see licence.txt in root directory, or project website".
A license.txt don't exists in the root directory. And on the website I can't find anything, too.
But as
http://www.osfree.org/doku/en:status
is mentioned that most parts are under the "osFree license" withount mentioning the license itself.
The 4OS2 license file on the other side exits
https://github.com/osfree-project/osfree/blob/master/OS2/CMD/cmd/license.txt

**Comment by prokushev** [comment]
in mos cases 4-clause bsd like license and gpl/lgpl licenses

**Comment by valerius2k** [comment]
Licenses are specific to each program. Usually, there should be a license.txt file in each program subdirectory. If not, it's usually, 3-clause BSD license. See http://osfree.org/doku/en:legal for details.

**Comment by theuserbl** [comment]
@valerius2k: Thanks. Thats what I wantet. :-)
