### ISSUE TITLE
Want new binaries

### ISSUE THREAD

**Issue by theuserbl** [osfree-project/osfree#3]
Nice to see new activity on OS/free the last time.
But the ISO-files at
http://osfree.org/doku/en:download
http://osfree.org/doku/en:demo
ftp://ftp.warpspeed.dk/osFree/
are "a little bit" outdated.
Would be nice if a new version of it would be uploaded

**Comment by prokushev** [comment]
Well, we are working on updated version now. Release date is open yet.
