### ISSUE TITLE
Why don't using WINE parts for the Win32 subsystem?

### ISSUE THREAD

**Issue by theuserbl** [osfree-project/osfree#4]
In your TODO-file of the win32-subsystem you write, that it crashed.
https://github.com/osfree-project/osfree/blob/master/win32/TODO
If the WINE-license is the reason, why you don't integrate WINE-code for it: You know, that older WINE was under the MIT-license:
https://github.com/wine-mirror/wine/blob/master/LICENSE.OLD

Some month ago I have still downloaded anywhere. But I no longer don't where it was.
So I asked now in the WINE-forum for the MIT licensed WINE
https://forum.winehq.org/viewtopic.php?f=2&t=31070

The file was Wine-20020228.tar.gz

**Comment by theuserbl** [comment]
As I now mentioned in the WINE-forum, I have found it again.
You can find it at
https://github.com/wine-mirror/wine/releases?after=wine-20020509

Direct links to the files
https://github.com/wine-mirror/wine/archive/wine-20020228.zip
https://github.com/wine-mirror/wine/archive/wine-20020228.tar.gz

So if you want to add MIT-licensed code to osfree, here is some for your Win32-subsystem. :-)

**Comment by theuserbl** [comment]
Uuups. I now see, that process.h and thread.h are already WINE files.

**Comment by prokushev** [comment]
Win32 is not main goal now. But yes, Wine/Odin/ReactOS codebase will be reused..

**Comment by valerius2k** [comment]
Why use old MIT-licensed WINE? Ordinary WINE is good enough. We're accept different licenses, not BSD/MIT only. Our main code is 3-clause BSD, but other parts may have different licensing: http://osfree.org/doku/en:legal.

BTW, why are you asking here? We use http://osfree.org/doku/issue as an issue tracker, but not here.

Win32 subdirectory is not in the build system, it's broken.

**Comment by valerius2k** [comment]
For asking questions, the irc channel is better. (#osfree channel on EFnet).

**Comment by theuserbl** [comment]
Ok, thanks for your answers prokushev and valerius2k.
